/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/


//  Name: LiC++ - Let it Crash in C++ - Translate Example
//  Copyright: Boost Software License - Version 1.0 - August 17th, 2003
//  Author: Christoph Woskowski, cwo_at_zuehlke.com
//
//  Description:
//    This is the implementation of the translate example from the book
//    "Seven Languages in Seven Weeks" by Bruce A. Tate. The original
//    Erlang example code can be downloaded here:
//    https://pragprog.com/titles/btlang/source_code
//    An asynchronous translator expects strings to be translated entered by
//    the user and prints out the translation if the word is known. If the
//    word is unknown, it prints "don't understand".

#include "LiC++.h"

#include <iostream>

using namespace std;
using namespace LiCpp;

struct msg_request {
  msg_request(std::string _text): text(_text) {}
  std::string text;
};


void translator(pMsgBox incoming)
{
  incoming->wait()
  .handle_if<msg_request>(
  [&](msg_request const& msg) {
    return msg.text == "casa";
  },
  [&]() {
    std::cout << "house" << std::endl;
  }
  )
  .handle_if<msg_request>(
  [&](msg_request const& msg) {
    return msg.text == "blanca";
  },
  [&]() {
    std::cout << "white" << std::endl;
  }
  )
  .handle_default(
  [&]() {
    std::cout << "I don't understand." << std::endl;
  }
  );
}

#ifndef TEST

int main()
{
  pLiCppRuntime p_run = make_shared<LiCppRuntime>();
  ThreadId translator_id = p_run->spawn_messaging(translator);

  bool quit_pressed=false;
  std::thread char_thread(
  [&]() {
    while (!quit_pressed) {
      std::string in_data;
      std::cin >> in_data;
      if (in_data=="q") {
        quit_pressed=true;
      } else
        p_run->send_message(translator_id, msg_request(in_data));
    }
  }
  );

  while(!quit_pressed) {
    p_run->exec();
    std::this_thread::sleep_for(std::chrono::milliseconds(10));
  }

  char_thread.join();
  return 0;
}

#else

int main()
{
  pLiCppRuntime p_run = make_shared<LiCppRuntime>();
  ThreadId translator_id = p_run->spawn_messaging(translator);

  bool test_done=false;
  std::thread test_thread(
  [&]() {
    p_run->send_message(translator_id, msg_request("casa"));
    p_run->send_message(translator_id, msg_request("blanca"));
    p_run->send_message(translator_id, msg_request("humphrey"));

    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    test_done=true;
  }
  );

  while(!test_done) {
    p_run->exec();
    std::this_thread::sleep_for(std::chrono::milliseconds(10));
  }

  test_thread.join();
  return 0;
}

#endif
