/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/


//  Name: LiC++ - Let it Crash in C++ - Basic LiC++ Tests
//  Copyright: Boost Software License - Version 1.0 - August 17th, 2003
//  Author: Christoph Woskowski, cwo_at_zuehlke.com
//
//  Description:
//    This file contains some basic tests of the LiC++ runtime. Looping,
//    cyclic and messaging threads are created, started, paused, resumed,
//    killed, reanimated and finally killed again.

#include "LiC++.h"

using namespace std;
using namespace LiCpp;

void looping_func(function<void()> check_for_interruptions)
{
  for (;;) {
    check_for_interruptions();
    this_thread::sleep_for(chrono::milliseconds(100));
    cout << "tack" << endl;
  }
}

void cyclic_func()
{
  static auto last = chrono::system_clock::now();
  auto now = chrono::system_clock::now();
  if (chrono::duration_cast<chrono::milliseconds>(now - last).count() > 100) {
    cout << "tick" << endl;
    last = now;
  }
}

pLiCppRuntime p_run = nullptr;
ThreadId looping_id;
ThreadId cyclic_id;
ThreadId messaging_id;

void dummy_crash_handler(ThreadId crashed_id, pException exc_ptr)
{
}

void crash_handler(ThreadId crashed_id, pException exc_ptr)
{
  if ((p_run) && (crashed_id == looping_id)) {
    cout << "Resurrecting tack ones ..." << endl;
    p_run->register_crash_handler(dummy_crash_handler);
    looping_id = p_run->spawn_looping(looping_func);
  }
};

struct Storage {
  string text;
  enum {init,ping,pong} state;
  vector<string> texts;
};

struct msg_ping {};
struct msg_pong {};

void msg_handler(pMsgBox incoming, shared_ptr<Storage> storage)
{
  incoming->wait()
  .handle<msg_ping>(
  [&](msg_ping const& msg) {
    cout << "ping" << endl;
    this_thread::sleep_for(chrono::milliseconds(100));
    incoming->get_sender().send(msg_pong());
  }
  )
  .handle<msg_pong>(
  [&](msg_pong const& msg) {
    cout << "pong" << endl;
    this_thread::sleep_for(chrono::milliseconds(100));
    incoming->get_sender().send(msg_ping());
  }
  );
}


int main()
{
  p_run = make_shared<LiCppRuntime>();
  p_run->register_crash_handler(crash_handler);

  Storage storage;
  looping_id = p_run->spawn_looping(looping_func);
  cyclic_id = p_run->spawn_cyclic(cyclic_func);
  messaging_id = p_run->spawn_messaging<Storage>(msg_handler, move(storage));

  p_run->send_message(messaging_id, msg_ping());

  bool test_done=false;
  thread test_thread([&]() {
    this_thread::sleep_for(chrono::seconds(3));

    cout << "Pausing all ..." << endl;
    p_run->suspend_thread(looping_id);
    p_run->suspend_thread(cyclic_id);
    p_run->suspend_thread(messaging_id);

    this_thread::sleep_for(chrono::seconds(3));

    cout << "Resuming all ..." << endl;
    p_run->resume_thread(looping_id);
    p_run->resume_thread(cyclic_id);
    p_run->resume_thread(messaging_id);

    this_thread::sleep_for(chrono::seconds(3));

    cout << "Killing all ..." << endl;
    p_run->kill_thread(looping_id);
    p_run->kill_thread(cyclic_id);
    p_run->kill_thread(messaging_id);

    this_thread::sleep_for(chrono::seconds(3));

    cout << "Killing tack ..." << endl;
    p_run->kill_thread(looping_id);

    this_thread::sleep_for(chrono::seconds(3));

    test_done=true;
  });

  while (!test_done) {
    p_run->exec();
    this_thread::sleep_for(chrono::milliseconds(10));
  }

  test_thread.join();

  return 0;
}
