CPP      = g++ -D__DEBUG__ -DTEST
CC       = gcc -D__DEBUG__ -DTEST
OBJ      = LiCpp_translate_service_test.o
LINKOBJ  = LiCpp_translate_service_test.o
LIBS     = -static-libgcc -g3 -lpthread
INCS     = -I"../LiCpp"
CXXINCS  = -I"../LiCpp"
BIN      = LiCpp_translate_service_test
CXXFLAGS = $(CXXINCS) -g3 -std=c++11
CFLAGS   = $(INCS) -g3 -std=c++11
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

LiCpp_translate_service_test.o: LiCpp_translate_service.cpp
	$(CPP) -c LiCpp_translate_service.cpp -o LiCpp_translate_service_test.o $(CXXFLAGS)
